services:
  backend:
    build:
      context: ./django-shop
      dockerfile: Dockerfile.prod
    command: gunicorn shop_backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/django-shop/staticfiles
      - media_volume:/home/app/django-shop/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/django-shop/staticfiles
      - media_volume:/home/app/django-shop/mediafiles
    ports:
      - 1337:80
    depends_on:
      - backend

volumes:
  postgres_data:
  static_volume:
  media_volume: