apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: ${NGINX_IMAGE}
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /home/app/django-shop/staticfiles
              name: static-files
            - mountPath: /home/app/django-shop/mediafiles
              name: media-files
      volumes:
        - name: static-files
          persistentVolumeClaim:
            claimName: static-files-pvc
        - name: media-files
          persistentVolumeClaim:
            claimName: media-files-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31337
  type: NodePort
