apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-data
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/postgres-data"  # Change path as needed

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-volume
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/static-files"  # Change path as needed

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-volume-claim
spec:
  accessModes:
    - ReadWriteMan
