# # Pull base image
# FROM python:3.10.6
FROM python:3.10

# # Set environment variables
# # disables an automatic check for pip updates each time
# ENV PIP_DISABLE_PIP_VERSION_CHECK 1 
# # Python will not try to write .pyc files
# ENV PYTHONDONTWRITEBYTECODE 1
# # ensures our console output is not buffered by Docker
# ENV PYTHONUNBUFFERED 1

WORKDIR /shop_backend

# install system dependencies
# RUN apt-get update && apt-get install -y netcat

# # Install dependencies
COPY requirements.txt .
RUN pip3 install -r requirements.txt

# # Copy project
COPY . .

EXPOSE 8000
RUN mkdir logs
RUN mkdir /shop_backend/static

COPY ./entrypoint.dev.sh /
ENTRYPOINT ["sh", "/entrypoint.dev.sh"]
