name: ci

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Test
        run: |
          ls
          echo "Context: $context"
          echo "Working directory: $working-directory"

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./nginx  # Adjust the build context to ./nginx directory
          file: ./nginx/Dockerfile  # Dockerfile location
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/portfolio:nginx
